#!/bin/bash
Xvfb -screen 0 1024x768x16 -ac &
export DISPLAY=:0 ratpoison
x11vnc -storepasswd vnc /tmp/vncpass
x11vnc -rfbauth /tmp/vncpass -display :0 -forever &
java -jar selenium-server-standalone-2.39.0.jar